### ISSUE TITLE
ie8bug for checkbox&radio

### ISSUE THREAD

**Issue by xuexb** [xuexb/demo#1]
在IE8里选中判断不了

**Comment by xuexb** [comment]
发现ie8里

这样后者的属性没读出来

``` css
.ui-checkbox input:checked + span,
.ui-checkbox.checked span{
    background-position:0 -20px;
}
```

这样就没事

``` css
/*.ui-checkbox input:checked + span,*/
.ui-checkbox.checked span{
    background-position:0 -20px;
}
```
